using System;
using System.Collections.Generic;
using System.Text;

namespace NrkBrowser.Domain
{
    public class AutogeneratedMenuItem : Item
    {
        public AutogeneratedMenuItem(string id, string title) : base(id, title)
        {
        }
    }
}
